web:
  image: mautic/mautic
  links:
    - db:mysql
  env_file:
    - ./env
  environment:
    - HOST
  ports:
    - "80:80"
  volumes:
      - "./conf/cg-php.ini:/usr/local/etc/php/conf.d/cg-php.ini"
db:
  image: mariadb
  env_file:
    - ./env
